---
- hosts: db_hosts
  sudo: yes

  vars_files:
  - vars/main.yml

  roles:
#  - geerlingguy.repo-epel
  - ANXS.postgresql

  # tasks:
  # - name: install python-pip
  #   yum: name={{ item }} state=present
  #   with_items:
  #     - python-pip
  # - name: upgrade pip
  #   command: pip install --upgrade pip
